import { PrismaClient } from '@prisma/client';

const LANG = 'en-GB';

export async function seedModules(prisma: PrismaClient) {
  console.log('  📚 Seeding British English modules...');

  const modules = [
    // Module 1: Foundation (A2-B1)
    {
      id: `${LANG}:1`,
      languageCode: LANG,
      parentModuleId: null,
      title: 'Foundation',
      description: 'Building Conversational Confidence - Navigate everyday conversations with confidence',
      level: 'A2-B1',
      objectives: [
        'Navigate everyday conversations with confidence',
        'Understand and use essential British English phrases',
        'Grasp fundamental differences between British and other English varieties',
        'Build cultural awareness for common social situations',
      ],
      duration: '8-12 weeks',
      order: 1,
    },
    {
      id: `${LANG}:1A`,
      languageCode: LANG,
      parentModuleId: '1',
      title: 'Essential Daily Interactions',
      description: 'Greetings, shopping, transport, weather, and basic daily conversations',
      level: 'A2-B1',
      objectives: [
        'Greet people appropriately in different contexts',
        'Navigate shopping in British supermarkets and shops',
        'Order at cafés, pubs, and restaurants',
        'Use public transport confidently',
        'Make small talk about weather',
      ],
      duration: '3 weeks',
      order: 1,
    },
    {
      id: `${LANG}:1B`,
      languageCode: LANG,
      parentModuleId: '1',
      title: 'Building Social Connections',
      description: 'Introductions, hobbies, invitations, and social arrangements',
      level: 'A2-B1',
      objectives: [
        'Introduce yourself effectively',
        'Discuss hobbies and weekend plans',
        'Accept and decline invitations politely',
        'Make arrangements and suggest alternatives',
        'Handle misunderstandings gracefully',
      ],
      duration: '3 weeks',
      order: 2,
    },
    {
      id: `${LANG}:1C`,
      languageCode: LANG,
      parentModuleId: '1',
      title: 'Practical Life Management',
      description: 'Renting, banking, healthcare, utilities, and complaints',
      level: 'A2-B1',
      objectives: [
        'Rent accommodation and talk to landlords',
        'Handle banking and financial matters',
        'Register with GP and discuss health issues',
        'Deal with utilities and council services',
        'Make complaints politely but firmly',
      ],
      duration: '3 weeks',
      order: 3,
    },
    {
      id: `${LANG}:1D`,
      languageCode: LANG,
      parentModuleId: '1',
      title: 'Expanding Conversational Range',
      description: 'News, culture, opinions, storytelling, and abstract topics',
      level: 'A2-B1',
      objectives: [
        'Discuss news and current events',
        'Talk about films, TV, books, and culture',
        'Share travel experiences and plans',
        'Express opinions with appropriate hedging',
        'Tell engaging stories with narrative structure',
      ],
      duration: '3 weeks',
      order: 4,
    },

    // Module 2: Intermediate (B1-B2)
    {
      id: `${LANG}:2`,
      languageCode: LANG,
      parentModuleId: null,
      title: 'Intermediate',
      description: 'Developing Natural Fluency - Communicate spontaneously on wide range of topics',
      level: 'B1-B2',
      objectives: [
        'Communicate spontaneously on wide range of topics',
        'Understand different British accents',
        'Use idiomatic language naturally',
        'Navigate complex social and professional situations',
      ],
      duration: '12-16 weeks',
      order: 2,
    },
    {
      id: `${LANG}:2A`,
      languageCode: LANG,
      parentModuleId: '2',
      title: 'Mastering British Idioms and Expressions',
      description: 'Colloquialisms, banter, slang, and code-switching',
      level: 'B1-B2',
      objectives: [
        'Use 50+ idioms and expressions naturally',
        'Follow group conversations at natural speed',
        'Engage in light banter appropriately',
        'Understand major British accents',
        'Code-switch between registers',
      ],
      duration: '4 weeks',
      order: 1,
    },
    {
      id: `${LANG}:2B`,
      languageCode: LANG,
      parentModuleId: '2',
      title: 'Professional and Academic Communication',
      description: 'Interviews, meetings, presentations, academic discussions',
      level: 'B1-B2',
      objectives: [
        'Handle job interviews confidently',
        'Participate effectively in meetings',
        'Write professional emails in British style',
        'Navigate workplace hierarchies linguistically',
        'Use sophisticated hedging and diplomatic language',
      ],
      duration: '4 weeks',
      order: 2,
    },
    {
      id: `${LANG}:2C`,
      languageCode: LANG,
      parentModuleId: '2',
      title: 'Deep Cultural Immersion',
      description: 'British history, politics, arts, sports, and society',
      level: 'B1-B2',
      objectives: [
        'Discuss British history and culture with depth',
        'Understand cultural references in media',
        'Participate in discussions about British society',
        'Show awareness of regional and class differences',
        'Demonstrate cultural sensitivity in language choices',
      ],
      duration: '4 weeks',
      order: 3,
    },
    {
      id: `${LANG}:2D`,
      languageCode: LANG,
      parentModuleId: '2',
      title: 'Spontaneous Communication Mastery',
      description: 'Impromptu speaking, crisis handling, audience adaptation',
      level: 'B1-B2',
      objectives: [
        'Speak for 5+ minutes on any topic',
        'Self-correct fluently without breaking flow',
        'Handle unexpected situations with flexibility',
        'Use native-like fillers and hesitation patterns',
        'Adapt communication style to different contexts',
      ],
      duration: '4 weeks',
      order: 4,
    },

    // Module 3: Advanced (B2-C1)
    {
      id: `${LANG}:3`,
      languageCode: LANG,
      parentModuleId: null,
      title: 'Advanced',
      description: 'Achieving Sophisticated Expression - Express complex ideas with precision',
      level: 'B2-C1',
      objectives: [
        'Express complex ideas with precision and nuance',
        'Master subtle aspects of British communication',
        'Develop native-like intuition for appropriateness',
        'Engage in intellectual and abstract discussions',
      ],
      duration: '16-20 weeks',
      order: 3,
    },
    {
      id: `${LANG}:3A`,
      languageCode: LANG,
      parentModuleId: '3',
      title: 'Subtle Language Mastery',
      description: 'Subtext, euphemisms, sophisticated humor, diplomatic language',
      level: 'B2-C1',
      objectives: [
        'Detect subtext and implicit meaning',
        'Use euphemisms and indirect language naturally',
        'Demonstrate sophisticated humor understanding',
        'Navigate sensitive topics diplomatically',
        'Show native-like intuition for expression',
      ],
      duration: '5 weeks',
      order: 1,
    },
    {
      id: `${LANG}:3B`,
      languageCode: LANG,
      parentModuleId: '3',
      title: 'Intellectual and Abstract Discourse',
      description: 'Philosophy, ethics, theory, argumentation, rhetoric',
      level: 'B2-C1',
      objectives: [
        'Engage in hour-long intellectual discussions',
        'Construct sophisticated multi-layered arguments',
        'Use abstract vocabulary with precision',
        'Demonstrate British rhetorical patterns',
        'Challenge and defend ideas at high level',
      ],
      duration: '5 weeks',
      order: 2,
    },
    {
      id: `${LANG}:3C`,
      languageCode: LANG,
      parentModuleId: '3',
      title: 'Perfecting Pronunciation and Prosody',
      description: 'Intonation, rhythm, emotional expression, accent refinement',
      level: 'B2-C1',
      objectives: [
        'Achieve near-native pronunciation in familiar contexts',
        'Use appropriate intonation for all speech acts',
        'Demonstrate natural rhythm and pacing',
        'Express emotional range through prosody',
        'Adjust accent for clarity when needed',
      ],
      duration: '4 weeks',
      order: 3,
    },
    {
      id: `${LANG}:3D`,
      languageCode: LANG,
      parentModuleId: '3',
      title: 'Professional Excellence',
      description: 'High-stakes presentations, negotiations, leadership communication',
      level: 'B2-C1',
      objectives: [
        'Communicate at C-suite professional level',
        'Handle high-pressure situations confidently',
        'Demonstrate complete command of professional English',
        'Use industry vocabulary with native-like precision',
        'Show strategic communication skills',
      ],
      duration: '6 weeks',
      order: 4,
    },

    // Module 4: Mastery (C1-C2)
    {
      id: `${LANG}:4`,
      languageCode: LANG,
      parentModuleId: null,
      title: 'Mastery',
      description: 'Achieving Native-Like Proficiency - Function linguistically indistinguishable from natives',
      level: 'C1-C2',
      objectives: [
        'Function linguistically indistinguishable from educated native speakers',
        'Master all varieties and registers of British English',
        'Understand and produce creative language',
        'Develop personal voice and style',
      ],
      duration: 'Ongoing (20+ weeks)',
      order: 4,
    },
    {
      id: `${LANG}:4A`,
      languageCode: LANG,
      parentModuleId: '4',
      title: 'Creative Language Use',
      description: 'Wordplay, humor creation, neologisms, linguistic creativity',
      level: 'C1-C2',
      objectives: [
        'Create original, culturally appropriate humor',
        'Demonstrate creative linguistic playfulness',
        'Show native-like intuition for breaking rules',
        'Produce creative written work at native level',
        'Contribute to British English language community',
      ],
      duration: 'Ongoing',
      order: 1,
    },
    {
      id: `${LANG}:4B`,
      languageCode: LANG,
      parentModuleId: '4',
      title: 'Complete Register Command',
      description: 'All registers from street slang to highest formal, historical forms',
      level: 'C1-C2',
      objectives: [
        'Master all registers and styles completely',
        'Understand historical British English',
        'Achieve professional competence in specialized fields',
        'Command multiple British regional varieties',
        'Teach and explain British English to others',
      ],
      duration: 'Ongoing',
      order: 2,
    },
    {
      id: `${LANG}:4C`,
      languageCode: LANG,
      parentModuleId: '4',
      title: 'Cultural Insider Status',
      description: 'Complete cultural literacy, public discourse, mentoring',
      level: 'C1-C2',
      objectives: [
        'Function as cultural insider in all contexts',
        'Contribute to British cultural discourse',
        'Teach British English and culture effectively',
        'Maintain and develop native-like proficiency',
        'Integrate British English into personal identity',
      ],
      duration: 'Ongoing',
      order: 3,
    },
  ];

  for (const module of modules) {
    await prisma.module.upsert({
      where: { id: module.id },
      update: module,
      create: module,
    });
  }

  console.log(`    ✅ Created ${modules.length} modules`);
}

